--- !ditz.rubyforge.org,2008-03-06/project 
name: go-file
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: go-file
- !ditz.rubyforge.org,2008-03-06/component 
  name: registry
- !ditz.rubyforge.org,2008-03-06/component 
  name: doozer
- !ditz.rubyforge.org,2008-03-06/component 
  name: file
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-09-05 21:11:52.415267 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - First milestone release with some functionality.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-09-05 21:14:06.918774 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - Issues which need to be fixed for a complete release.
